### ISSUE TITLE
Flashing screen on iPad when object passes focal point

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/geometric-optics#103]
**Device**
iPad
**OS**
iPadOS 14
**Browser**
Safari
**Problem Description**
For https://github.com/phetsims/qa/issues/667. I wasn't able to get this to occur on Win 10 Chrome.
When on the mirror screen with a concave mirror, moving the object back and forth over the focal point would cause the screen to flash. It was inconsistent, so it may happen on on screens/scenes as well.
**Visuals**

https://user-images.githubusercontent.com/41024075/125131315-ce553c80-e0bf-11eb-9e19-e4098c94371e.MP4

**Comment by veillette** [comment]
The mirror equation (as well as the lens equation) is given by the sum of harmonics. This implies that there must be a discontinuous singularity for the position of the target.  

A slight change of position of the object (when crossing the focal point) can lead the target to go from a position of +infinity to - infinity.
Since a target at infinity as infinite height, its size can bleed into the play area.  I had previously thought that since we are also adjusting the opacity of the target (which goes to zero at infinity), this would not be a problem that needed to be handled.

To prevent this from happening, we can make the target invisible if the target is very far away from the optic.

**Comment by veillette** [comment]
A similar phenomenon should be present in the lens screen as well.

**Comment by veillette** [comment]
On second thought, I am not sure if this is a bug, but a "feature". 

When one is walking toward a large concave mirror, there is a singularity at the focal point where your reflection goes from being inverted to upright.  The reflection gets incredibly and distorted (because irregularities in the mirror surface get amplified at the focal point). In some ways, this "flashing" of the screen illustrates that there is something very singular that happened when the object crosses the focal point.

**Comment by veillette** [comment]
I'll assign the meeting-label, such that we can discuss it with the design team.

**Comment by veillette** [comment]
We discussed it during the 7/13 design meeting.

**Comment by arouinfar** [comment]
In the 7/13 design meeting, we discussed the possibility of hiding the image when it becomes sufficiently large. However, given the zoom range, it's possible to create very large images that aren't the result of the singularity.  It's quite tricky to place the object exactly at the focal point, and when a user succeeds, the physics is correct.  I don't think we need to do anything here, aside from noting it in the Teacher Tips.
