### ISSUE TITLE
Move Second Source to a new Node, so that it can be on top of the lightrays.

### ISSUE THREAD

**Issue by veillette** [phetsims/geometric-optics#120]
The z-layer of the second source and cueing arrows should be change. They should be on top of the lightrays.

**Comment by kathy-phet** [comment]
If trivial, do this for the prototype.

**Comment by pixelzoom** [comment]
@arouinfar please clarify, preferrably with a screenshot.  What is "the dot" and "cueing arrows"?

**Comment by arouinfar** [comment]
@pixelzoom this issue is referring to the "Second Source" which appears as a red dot on the picture frame objects. The dot and cueing arrows should be layered on top of the rays, because it can get occluded fairly easily:
![image](https://user-images.githubusercontent.com/8419308/133329150-3a779bb3-7f70-4ef5-ba3a-336ff4a26938.png)

**Comment by pixelzoom** [comment]
This is going to be a major change, because the "Second Source" (red dot) is currently part of the same node as "the Object".   They will need to be broken up into 2 Nodes, so that the Second Source can be put on top.

**Comment by pixelzoom** [comment]
@kathy-phet said:
> If trivial, do this for the prototype.

This is not going to be trivial. It's a major change, because the "Second Source" (red dot) is currently part of the same node as "the Object" (SourceObjectNode.js).   They will need to be broken up into 2 Nodes, so that the Second Source can be put on top.

@arouinfar @kathy-phet please advise whether you want me to continue.

**Comment by arouinfar** [comment]
@pixelzoom we can skip this for the prototype. I'll tag for design meeting to determine if it's worth pursuing for the full release.

**Comment by pixelzoom** [comment]
I'm going to add this back to the Prototype Sim milestone https://github.com/phetsims/geometric-optics/milestone/1.  Despite the fact that it's not trivial, it really needs to be done.  SourceObjectNode.js has way too many responsibilities. And the fact that it's responsible for the Second Source, and the Second Source's cueing arrows, is making https://github.com/phetsims/geometric-optics/issues/143 (add cueing arrows) very complicated.

**Comment by pixelzoom** [comment]
I was trying to avoid doing this over in #143. But I got far enough into decoupling source object and second source that I went for it.  The second source is now in front of the rays.  The only thing that's in front of the second source now are the focal points. 

@arouinfar please review in master.

**Comment by pixelzoom** [comment]
Reviewed in 9/23/21 dsign meeting. Looks good. Closing.
