### ISSUE TITLE
Rays should look like they're passing through things.

### ISSUE THREAD

**Issue by sarchang** [phetsims/geometric-optics#125]
(This comment was edited by @pixelzoom.)

The optical axis should appear to poke through the object and the image (real and virtual). 

The optical axis should also appear to poke through the projection screen, to prevent a 3D optical illusion effect.

Ditto for rays.

This should not apply to light sources.

**Comment by veillette** [comment]
This should not apply to light sources.

**Comment by pixelzoom** [comment]
Moving the optical axis part of this to https://github.com/phetsims/geometric-optics/issues/283, since it's going to be a separate chunk of work.

**Comment by pixelzoom** [comment]
From https://github.com/phetsims/geometric-optics/issues/283#issuecomment-999803267:

> * For rays in #125:
>   - For real image, use this same approach.
>   - For virtual image, do nothing. Do not want the rays to look like they're going through the (solid) object.
>   - For projection screen, do nothing, the current look is desired.

**Comment by pixelzoom** [comment]
Similar to what I did in #283 with `opticalAxisNode` and `opticalAxisForegroundNode` ....  I'll need to create `LightRaysForegroundNode extends LightRaysNode`.  Then in GOScreenView.js:

```js
const lightRays1Node = new LightRaysNode( ... );
const lightRays2Node = new LightRaysNode( ... );
const lightRays1ForegroundNode = new LightRaysForegroundNode( ... );
const lightRays2ForegroundNode = new LightRaysForegroundNode( ... );
```

... and adjust the rendering order.

**Comment by pixelzoom** [comment]
In the above commit, I did what I described in https://github.com/phetsims/geometric-optics/issues/125#issuecomment-1005279902.   `?debugRays` renders the foreground rays with 'red' stroke.

As mentioned in https://github.com/phetsims/geometric-optics/issues/283#issuecomment-1005269120, the mask for the image is currently not ideal, and won't be correct until phetsims/scenery#1333 is addressed.

**Comment by pixelzoom** [comment]
@arouinfar This is ready for review in master.  The current opacity of the image mask is 0.8. Let me know if you'd like to see more or less of the occluded rays.  Note that this opacity will also affect how much of the occluded optical axis is seen.

**Comment by pixelzoom** [comment]
Ugh, this is not working correctly for mirror + real image, see screenshot below.  Back to the drawing board...

<img width="1044" alt="screenshot_1491" src="https://user-images.githubusercontent.com/3046552/148296017-8f3c0983-6f39-4bef-b4ee-aed0c5884c8c.png">

**Comment by pixelzoom** [comment]
I'm not sure what to do here, because @arouinfar and I didn't talk about the mirror.  In the screenshot below, should the rays looks like they are going through the real Image only, and not look like they are going through the Object? 

<img width="1043" alt="screenshot_1492" src="https://user-images.githubusercontent.com/3046552/148296225-c7ad3471-8d20-4578-af41-752ee9433e77.png">

**Comment by pixelzoom** [comment]
Discussed with @arouinfar on Zoom.

Here are the rules for when rays should go through something:

* Rays should never go through the Object, they should always appear in front of the Object.

* Prior to interacting with the optic, rays should never go through the Image, because the Image doesn't exist until the rays have interacted with the object.

* After interacting with the optic, rays should appear to go through the Image.

* Rays are blocked by the projector screen, and do not continue past the screen.

* Reflected rays are not blocked by the Object, and continue past the Object, passing in front of the Object.

**Comment by pixelzoom** [comment]
Two remaining problems:

(1) The performance of dragging the object has gotten worse. I'm not sure exactly when it got worse, but it's really noticeable with "Many" rays.  I'll need to look back through dev versions.  Tracking in https://github.com/phetsims/geometric-optics/issues/286.

(2) There's 1 case that I can't work around, shown below.  The rays between the object and optic should not appear to go through the image.   With this clipArea approach, I can't do anything about this, because all rays are rendered by one Node.  I would need to split that Node into 2 Nodes -- one Node for rays between the object and optic, one Node for rays leaving the optic.  I'll defer this for now, because work on https://github.com/phetsims/geometric-optics/issues/140 might offer a solution.

![screenshot_305](https://user-images.githubusercontent.com/3046552/148464362-e1889580-e140-44e1-a262-0a07ab9200be.png)

**Comment by pixelzoom** [comment]
I really don't like this approach of having rays sometimes stay in the 2D plane, and sometimes pass in front of things. It's conceptually confusing, and has turned into a nightmare to implement.  I think we should keep rays in the 2D plane, allow them to pass through things that are not opaque (real and virtual image), and have them be blocked by things that are solid (Object, projection screen).

**Comment by pixelzoom** [comment]
I'm going to pause work on this until we decide how to address https://github.com/phetsims/geometric-optics/issues/288 (physics bug with concave mirror).   If we constrain dragging in the Mirror screen as described in https://github.com/phetsims/geometric-optics/issues/288#issuecomment-1010350856, then the remaining problems here should go away (or be much easier to solve).

**Comment by kathy-phet** [comment]
I personally like the idea of everything passing through or being blocked at the center axis, and not having some rays overlay on the very top layer. It's feeling kind of confusing when it overlays on top.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/geometric-optics/issues/288, the Object is now constrained to horizontal dragging above the optical axis.  There are still some bothersome cases where rays pass in front of the Object, examples below.

@arouinfar What do you want to do about this?  As with the performance problem in https://github.com/phetsims/geometric-optics/issues/286#issuecomment-1011412317, my recommedation remains the same: replace the 3D framed objects with 2D objects.

<img width="1286" alt="screenshot_1529" src="https://user-images.githubusercontent.com/3046552/150032097-d88a1c92-af83-437a-be24-d5523db0cfd7.png">
<img width="1286" alt="screenshot_1530" src="https://user-images.githubusercontent.com/3046552/150032106-e387ea8c-c450-481c-9b90-48a29af007c7.png">
<img width="1275" alt="screenshot_1531" src="https://user-images.githubusercontent.com/3046552/150032110-07d54718-0e98-42ce-b587-97fa53cf8489.png">

**Comment by kathy-phet** [comment]
Before going down the road of replacing 3D with 2D, I think a design meeting to mock up what it would look like would be preferable. And I would recommend including MD in discussion/ideation too .... pedagogically my preference is the picture frames because we are not modeling the depth at all, and picture frame really makes that clear as this aspect of things being in a plane and when something is in focus.

**Comment by kathy-phet** [comment]
I can test on the kids school chromebook re performance, if useful.

**Comment by pixelzoom** [comment]
Ugh. Rays are still not right for the 2nd point, see below.   This seems to be the case whenever the 2nd point on the Image is above the optical axis.

Back to the drawing board :(

<img width="1258" alt="screenshot_1532" src="https://user-images.githubusercontent.com/3046552/150039492-2eaec914-5a3f-48e6-9fed-6e7cf4586a92.png">
<img width="1285" alt="screenshot_1533" src="https://user-images.githubusercontent.com/3046552/150039568-abb5c974-1dde-4701-8bf7-b49401581405.png">

**Comment by pixelzoom** [comment]
The problem in is due the clipArea not being properly translated.   In the above commit, I added rendering of the clipArea with `?debugRays`, and this is what it looks like (red rectangle):

![screenshot_319](https://user-images.githubusercontent.com/3046552/150235717-b27205a8-fb3e-497e-958a-803d08f431dd.png)

This was indeed a problem in 1.1.0-dev.14 and earlier, but only noticeable when you zoomed out.  Here's `?debugRays` in 1.1.0-dev.14, when zoomed out.  clipArea  rendering had not been added in this version, but the red rays are the ones the are inside the clipArea.

![screenshot_318](https://user-images.githubusercontent.com/3046552/150235627-77a26da1-d311-42ac-92af-3174d1d17ec3.png)

So it's not worth reverting https://github.com/phetsims/geometric-optics/commit/a9b9e6a1dc049eff14f1ea3c0a9dc9ae72f91c62 for #277 to address this. It was broken before that change was made, just less obvious.

**Comment by pixelzoom** [comment]
The problem noted in https://github.com/phetsims/geometric-optics/issues/125#issuecomment-1015952157 is fixed in the above commits, published in [1.1.0-dev.17](https://phet-dev.colorado.edu/html/geometric-optics/1.1.0-dev.17/phet/geometric-optics_en_phet.html).

Assigned to @arouinfar for guidance on the cases where a ray appears to pass in front of the Object, as shown in https://github.com/phetsims/geometric-optics/issues/125#issuecomment-1015908897.  What would make the most sense to me is to have the rays stop at the Object. But that would require significant changes to the ray-tracing code - which I have so far managed not to touch much.

**Comment by ariel-phet** [comment]
@pixelzoom for the problems noted in https://github.com/phetsims/geometric-optics/issues/125#issuecomment-1015908897 I think only the 2nd and 3rd case are egregious. However, in those case I do think the most correct thing would be to have the rays stop at the object, despite the unfortunate nature of modifications to the ray-tracing code.

**Comment by pixelzoom** [comment]
1/20/22 design meeting:

We all agreed that it would be preferable to not have rays going through the Object. But this could be costly, and would also involve adding information about the height (bisector line) of the framed objects.   I'll do 1-2 hours of exploration and report back.

**Comment by pixelzoom** [comment]
In LightRay.js, here's the code that handles termination of a ray on the projection screen.  Terminating a ray on the Object would probably involve something similar.

```js
    // If we have a projection screen, check whether the last ray intersects the projection screen,
    // and therefore terminates at the projection screen.
    if ( projectionScreen ) {
      setFinalPointOnProjectionScreen( this.realRays, projectionScreen.getBisectorLineTranslated() );
    }
```

**Comment by pixelzoom** [comment]
> We all agreed that it would be preferable to not have rays going through the Object. But this could be costly, and would also involve adding information about the height (bisector line) of the framed objects. I'll do 1-2 hours of exploration and report back.

It wasn't too difficult to locate the relevant ray-tracing code, and clean it up so that it could be used to terminate rays at the Projection Screen or the Object.

There are 2 additional changes that would need to be made:
* add a bisection line for "framed objects" to the model (non-trivial)
* modify the ray clipArea used for mirrors (relatively easy)

Before making any big changes, I added a hard-coded bisection line, just so I could see what it looks like. And what I saw concerned me. The representation for rays has no directionality, and you only see directionality when rays animate (when changing Rays radio buttons, or pressing Show/Hide button).  So when looking at the static "picture", reflected rays that _stop at_ the Object might be misinterpreted as rays that _originate from_ the Object.  

Below are screenshot for 2 scenarios, comparing "Object blocks reflected rays" vs "Reflected rays pass in front of Object".

I discussed this with @arouinfar.  She doesn't want to add directional indicators (e.g. arrows) to the rays, and I agree.  While both approaches have problems, "reflected rays pass in front of Object" seems to be the less-problematic approach, and could be noted in Teacher Tips.  So we're incline to allow reflected arrays to pass in front of Objects. 

@arouinfar @kathy-phet do you agree?

---
### SCENARIO 1: Concave Mirror

Object blocks rays:
![screenshot_327](https://user-images.githubusercontent.com/3046552/150584913-fc9600b4-732a-4410-9ec4-4298e3335e3a.png)

Reflected rays pass in front of Object:
![screenshot_328](https://user-images.githubusercontent.com/3046552/150584924-3afd7b5d-26db-4bca-98e0-2c9d7989f155.png)

---
### SCENARIO 2: Convex Mirror

Object blocks rays:
![screenshot_329](https://user-images.githubusercontent.com/3046552/150584928-81789374-1300-43b7-a624-f77350311243.png)

Reflected rays pass in front of Object:
![screenshot_330](https://user-images.githubusercontent.com/3046552/150584969-25d6e9a1-283b-4e5d-83ba-d879511ef1aa.png)

**Comment by pixelzoom** [comment]
While I did commit some cleanup of the ray tracer in https://github.com/phetsims/geometric-optics/commit/dd8f0bd1da80205aa757915d5e3953f6d3eb39a9, I did not commit the changes used to make the above screenshots.  Here's a patch in case we decide to continue with the "Objects block rays" approach.  

<details>
<summary>Patch</summary>

```diff
Index: js/common/model/LightRays.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/model/LightRays.ts b/js/common/model/LightRays.ts
--- a/js/common/model/LightRays.ts	(revision 4feef7c190e5a9a863f58f9547009e573d52051f)
+++ b/js/common/model/LightRays.ts	(date 1642784666596)
@@ -100,7 +100,7 @@
 
           // determine the lightRay
           const lightRay = new LightRay( initialRay, time, optic, targetPoint, isVirtual, isPrincipalRaysType,
-            representation.isObject ? null : projectionScreen
+            representation.isObject ? null : projectionScreen, sourceObjectPositionProperty
           );
 
           // set target's visibility to true after the first ray reaches its target
Index: js/common/model/LightRay.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/model/LightRay.ts b/js/common/model/LightRay.ts
--- a/js/common/model/LightRay.ts	(revision 4feef7c190e5a9a863f58f9547009e573d52051f)
+++ b/js/common/model/LightRay.ts	(date 1642791123924)
@@ -22,6 +22,8 @@
 import LightRaySegment from './LightRaySegment.js';
 import Optic from './Optic.js';
 import Ray from './Ray.js';
+import Shape from '../../../../kite/js/Shape.js';
+import IReadOnlyProperty from '../../../../axon/js/IReadOnlyProperty.js';
 
 class LightRay {
 
@@ -51,9 +53,11 @@
    * @param isVirtual - is the image virtual?
    * @param isPrincipalRaysType - is the light ray mode set to Principal rays
    * @param projectionScreen - optional projection screen that can block the rays
+   * @param sourceOjectPositionProperty
    */
   constructor( initialRay: Ray, time: number, optic: Optic, targetPoint: Vector2, isVirtual: boolean,
-               isPrincipalRaysType: boolean, projectionScreen: ProjectionScreen | null ) {
+               isPrincipalRaysType: boolean, projectionScreen: ProjectionScreen | null,
+               sourceOjectPositionProperty: IReadOnlyProperty<Vector2> ) {
 
     assert && AssertUtils.assertNonNegativeNumber( time );
 
@@ -68,11 +72,14 @@
 
     this.realRays = getRealRays( initialRay, firstPoint, optic, isPrincipalRaysType, targetPoint );
 
-    // If we have a projection screen, check whether the last ray terminates on the projection screen.
-    if ( projectionScreen ) {
-      const lastRay = this.realRays[ this.realRays.length - 1 ];
+    // Check whether the last ray terminates on the projection screen or source object.
+    const lastRay = this.realRays[ this.realRays.length - 1 ];
+    if ( projectionScreen ) {
       terminateOnProjectionScreen( lastRay, projectionScreen );
     }
+    else if ( optic instanceof Mirror ) {
+      terminateOnFramedObject( lastRay, sourceOjectPositionProperty.value );
+    }
 
     this.hasVirtualRay = hasVirtualComponent( isVirtual, this.realRays );
 
@@ -279,6 +286,29 @@
   return initialRay.position.blend( firstPoint, opticSourceVector.x / firstSourceVector.x );
 }
 
+/**
+ * If ray intersects the framed object, terminate the ray on the framed object by setting
+ * the ray's final point.
+ * @param realRay
+ * @param sourceObjectPosition
+ */
+function terminateOnFramedObject( realRay: Ray, sourceObjectPosition: Vector2 ): void {
+
+  //TODO This line was created empirically because it does not currently exist in the SourceObject model.
+  //TODO Factor out duplication with terminateOnProjectionScreen.
+  const bisectorLine = new Shape().moveToPoint( sourceObjectPosition.plusXY( 0, 18 ) ).lineToPoint( sourceObjectPosition.minusXY( 0, 72 ) );
+
+  const intersection = bisectorLine.intersection( realRay );
+
+  // {Vector2|null}
+  const pointOnScreen = getPoint( intersection );
+
+  // If intersection is found, set the transmittedRay final point
+  if ( pointOnScreen ) {
+    realRay.setFinalPoint( pointOnScreen );
+  }
+}
+
 /**
  * If ray intersects the projection screen, terminate the ray on the projection screen by setting
  * the ray's final point.
```

</details>

**Comment by pixelzoom** [comment]
If you'd like to test-drive the "Object blocks reflected rays" approach, see [1.1.0-dev.18](https://phet-dev.colorado.edu/html/geometric-optics/1.1.0-dev.18/phet/geometric-optics_en_phet.html).

I reverted [changes](https://github.com/phetsims/geometric-optics/commit/75cf430457d1bca08a9cf5888beb6a7ce1bfb591) after publishing that dev version.

**Comment by arouinfar** [comment]
@pixelzoom I am confident in our decision to allow reflected rays to pass over the object. I've made a note to document this behavior in the Teacher Tips, so I'll go ahead and close.
