### ISSUE TITLE
Address confusion related to Principal rays

### ISSUE THREAD

**Issue by sarchang** [phetsims/geometric-optics#140]
Some students were confused when comparing Many Rays to Principal Rays because in Many Rays, rays that don't pass through the optic are straight, but in Principal Rays, rays that don't pass through the optic are still reflected/refracted.
![image](https://user-images.githubusercontent.com/29347882/127383807-2822fdd2-fbf0-44d8-b925-7f0a36c17462.png)
![image](https://user-images.githubusercontent.com/29347882/127383771-b2bb0b6a-8f5d-4dfb-9fe4-8ea0221fa4fe.png)

The top and bottom principal rays should be dashed lines to emphasize that they do not represent real light rays like the ones in Many Rays.

**Comment by veillette** [comment]
To clarify, only the portion of the ray that extends beyond  vertical optic line (but without passing through the optic) should be dotted.

In the case of the mirror, the "reflected" ray should be dotted if the ray does not go hit the mirror.

**Comment by pixelzoom** [comment]
I wasn't totally clear on what is desired here, so I discussed with @arouinfar on Zoom.  

Several of the comments above refer to "dotted" lines.  Dashed lines are desired, not dotted.

The screenshots below show the 4 scenarios that we need to handle. The red arrows point to the ray segments that should be dashed. 

Lens + Real Image:

![140-lens-real](https://user-images.githubusercontent.com/3046552/148300409-03c11340-b113-463c-a1db-59c9f82db3c4.jpg)

Lens + Virtual Image:

![140-lens-virtual](https://user-images.githubusercontent.com/3046552/148300414-005f23d3-c506-4690-8d8f-d51f7836eb6c.jpg)

Mirror + Real Image:

![140-mirror-real](https://user-images.githubusercontent.com/3046552/148300456-5855056e-b7e0-44aa-82ff-151c6737338a.jpg)

Mirror + Virtual Image:

![140-mirror-virtual](https://user-images.githubusercontent.com/3046552/148300485-3ada024e-dd70-4253-a031-ffb90cde52fd.jpg)

**Comment by pixelzoom** [comment]
@arouinfar proposed that virtual rays would look nicer using dashed line style.  I prototyped this, ran it past @arouinfar, and she liked it.  So it's implemented in the above commit.  The screenshot below shows an example.

This make it problematic to use a dashed line style for some of the real ray segments. I have some other ideas for how to address that, which I'll work on next.

<img width="1044" alt="screenshot_1515" src="https://user-images.githubusercontent.com/3046552/149033361-8511ceb1-a47f-434b-b74a-6d252d2a2e69.png">

**Comment by pixelzoom** [comment]
I don't think that using a different line style for specific segments of real rays is not going to prevent confusion. It didn't help me undertand this.  What did help was @ariel-phet describing it to me, particularly the bit about thinking of the optic as extended infinitely. 

So I think a better approach is to:
* use the same line style for all real ray segments
* provide teacher tips and other scaffolding to discuss Principal rays
* modify the vertical axis to help support the "infinite optic" concept

I did a quick prototype, showed it to @arouinfar and @ariel-phet, refined it and pushed in the above commit. Screenshot shown below.

<img width="1045" alt="screenshot_1517" src="https://user-images.githubusercontent.com/3046552/149035994-37989f56-fcd6-4c14-b9a1-5cb636f82410.png">





Rather than use a dashed line style for specific real ray segments, it might be better to support the concepts involved in understanding physical rays,

**Comment by pixelzoom** [comment]
So to summarize, the proposal for addressing this issue is:

* Provide teacher tips and other resources related to Principal rays.
* Modify the look of the vertical axis to support those resources.

@arouinfar please review.

**Comment by arouinfar** [comment]
I completely agree. Thanks for summarizing @pixelzoom. I've also added this issue to the Teacher Tips issue.

 The vertical axis in https://github.com/phetsims/geometric-optics/issues/140#issuecomment-1010450253 looks like an extension of the lens, and I'm happy with that look. 

Things look a bit off in master (vertical axis only extends below optical axis), however, so back to @pixelzoom to investigate.
<img src="https://user-images.githubusercontent.com/8419308/150035046-7015f5d8-da7b-4e18-9d26-1751599d9da3.png" width=150>

**Comment by pixelzoom** [comment]
@arouinfar said
> Things look a bit off in master (vertical axis only extends below optical axis), however, so back to @pixelzoom to investigate.

Handling that problem in #298, so closing this issue.
