### ISSUE TITLE
Add double-headed cueing arrow to object

### ISSUE THREAD

**Issue by sarchang** [phetsims/geometric-optics#143]
See pH scale for example:
![image](https://user-images.githubusercontent.com/29347882/127384734-5f4e1e90-5899-45e7-b048-2b6efd16fc55.png)
Should be a connected double arrow head. Use arrowNode.

Should disappear after the first time a user moves the object. Should be present for all representations of the object until the user moves any of the objects. For the spotlight option, it should only appear for the first blue lamp. Cueing arrows in the lens and mirror screen are independent.

**Comment by pixelzoom** [comment]
@arouinfar Which "objects" does this refer to?  And do you really want cueing arrows on everything that is draggable?

**Comment by arouinfar** [comment]
"Object" is specific optics terminology, sorry. Light travels from the object to the lens/mirror. In this case, "object" refers to the item to left of the lens/mirror -- the picture frame/lamp. If you turn on the Labels checkbox, the object will be labeled.

**Comment by pixelzoom** [comment]
Note to self: in the source code, this is SourceObjectNode.js.

**Comment by pixelzoom** [comment]
I was a bit confused because SourceObjectNode.js already has something referred to in the code as "cueing arrows".   But I think its the red arrows that appear around the red dot, visible when "Second Source: checkbox is checked.  See the screenshot below. 

These red cueing arrows do not disappear when you start dragging, but instead disappears when you release the pointer at the end of the drag.  This is not the usual behavior for cueing arrows.  @arouinfar do you want me to change this, so that the arrows disappear as soon as the red dot is moved?

<img width="780" alt="screenshot_1236" src="https://user-images.githubusercontent.com/3046552/133329730-d3bc3755-f995-43fa-b5f3-9cb12a9691c3.png">

**Comment by pixelzoom** [comment]
@arouinfar please also confirm:

* The red dot should also presumable have `cursor: 'ns-resize'` (up/down arrows) since it can only be moved up/down. 

* The new cueing arrows that you'd like added to the source object should disappear as soon as the object is moved, not when the object is released at the end of a drag.

**Comment by pixelzoom** [comment]
@arouinfar for answering the above questions, it may be useful to review the decisions that were made in https://github.com/phetsims/geometric-optics/issues/81 for the Second Source cueing arrows.

**Comment by pixelzoom** [comment]
This has been way more complicated than it should have been, because of https://github.com/phetsims/geometric-optics/issues/120.  

What I've done so far:

* Added cueing arrows to the Source Object.  They have the same proportions as the Second Source cueing arrows.  They're on the left side of the Source Object, they scale with the Source Object, they disappear when you move the Source Object, they return after Reset All.

* Second Source cueing arrows now disappear as soon as you move the Second Source, instead of when you end the drag.  This is consistent with behavior of cueing arrows in other sims.

* Second Source "dot" and cueing arrows have the up/down cursor, instead of the hand cursor, because you can only move them up/down.  This is consistent with other sims that constrain dragging to 1 dimension.

What I still need to do:

* Cueing arrows for Source Object have are not interactive - they cannot be dragged to move the Second Source - and they do not have a hand cursor.  Before I can do this properly, SourceObjectNode.js needs to be split up, so that the Secound Source is in a separate Node -- as described in https://github.com/phetsims/geometric-optics/issues/120.

@arouinfar please review what I've done so far, since I proceeded before getting your answers to questions in https://github.com/phetsims/geometric-optics/issues/143#issuecomment-919494602.

**Comment by pixelzoom** [comment]
At 9/17/21 design meeting, we decided that our first milestone should be to publish a prototype, hopefully in the next could of weeks.  So I'm going to take another look at finding a quick-&-dirty way to make the cueing arrows interactive, so that we don't need to address #143 for the prototype. 

@arouinfar please hold off on reviewing this issue, and I'll assign back to you when I'm done.

**Comment by pixelzoom** [comment]
Discussed questions from https://github.com/phetsims/geometric-optics/issues/143#issuecomment-919494602 with @arouinfar via Zoom.   She'd like the cueing arrows to disappear on end drag, since dragging the green arrows may otherwise look odd.   Done in the abov commit.

**Comment by pixelzoom** [comment]
Both cueing arrows (source object and second source) are now interactive, and disappear when the drag ends.  @arouinfar please review in master.

**Comment by pixelzoom** [comment]
9/23/21 design meeting:  Looks good, closing.
