### ISSUE TITLE
performance testing and sign-off

### ISSUE THREAD

**Issue by veillette** [phetsims/geometric-optics#149]

**Comment by veillette** [comment]
This is a "standard GitHub issue" in the code-review checklist. The lead designer must sign off on performance. 
The most current dev at present time is 
https://phet-dev.colorado.edu/html/geometric-optics/1.0.0-dev.8/phet/geometric-optics_en_phet.html

**Comment by veillette** [comment]
Assigning to @arouinfar although it may be preferable to do this performance sign-off on an RC instead.

**Comment by arouinfar** [comment]
@ariel-phet if you have an iPad, could you do some performance testing? Things feel snappy on my MacBook Pro, but I won't have access to our QA devices until sometime next week.

**Comment by ariel-phet** [comment]
@arouinfar I no longer have an iPad (I gave the PhET one back to QA awhile back).

**Comment by pixelzoom** [comment]
The sim has been feature-complete for a couple of weeks, and I've completed all major changes.  I'm expecting additional code changes to be minor "polishing".  So this sim is ready for performance testing and sign-off @arouinfar.

**Comment by arouinfar** [comment]
@pixelzoom I'll be able to test out the performance on iPad and Chromebook when I'm in the office next Monday. I did some testing on my phone, and things generally seem good. The only issue I've noticed is that things can get pretty jerky when dragging the object through the focal point. When Do = f, Di = Infinity, so I imagine that's causing the stutter. It's noticeable even on my new MacBook Pro and pretty laggy on my phone.

**Comment by pixelzoom** [comment]
Thanks @arouinfar.  I'm not aware of anything that should impact performance when Do = f, so self-assigning to investigate.

**Comment by arouinfar** [comment]
@pixelzoom I tested on iPadOS 14 and Chromebook, and the performance is looking good. The fix in #361 dramatically improved the performance on both platforms.

On Chromebook, the worst case appears to be: framed object, second point on, many rays. Dragging the object around can be fairly laggy, but within acceptable levels. Otherwise, the performance is fine. It's not as snappy as other platforms, but it's not noticeable unless doing a side-by-side comparison.
