### ISSUE TITLE
Lots of overlapping labels when zoomed out

### ISSUE THREAD

**Issue by zepumph** [phetsims/geometric-optics#159]
I feel a bit like this is likely a known issue by the team, but just in case you want to discuss further. It is quite easy to find that labels overlap 

![image](https://user-images.githubusercontent.com/6856943/128196025-cf2df00d-55be-4c2c-86c8-2bad4a552ea2.png)

I can imagine this could be a challenge to fix generally. Perhaps it would be good to check in with a designer before working on it. Over to @arouinfar (responsible designer as said by https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md)

**Comment by arouinfar** [comment]
Thanks @zepumph.

Looks like there may have been some recent changes to the labels/layout, because the static objects no longer have overlapping labels when zoomed all the way out:
![image](https://user-images.githubusercontent.com/8419308/135663210-cec28cf5-2449-4d79-a8a2-8d41f69fcf6d.png)

I'm not particularly concerned by the labels associated with movable objects occasionally overlapping the static labels, so I'll go ahead and close.
