### ISSUE TITLE
Consider renaming first and second focal point. 

### ISSUE THREAD

**Issue by veillette** [phetsims/geometric-optics#170]
The name first and second focal points refer to their position with respect to the optic.
https://www.topperlearning.com/answer/i-wanted-to-know-about-first-principal-focus-and-second-principal-focus/iysbu1ll

Their name allows to distinguish between the two of them, using some standard language of optics.

However, in #164, it was noted that there is a false equivalence between first and second focal point and first/second source, and first and second/target.

Externally, we do not label the two focal points differently and therefore we never leverage the language distinctions that is used internally. 

@MK suggested using positiveFocalPoint and negativeFocalPoint, which would break that parallelism. We can note in the comments the  optical term used for these two points.

**Comment by pixelzoom** [comment]
I'm not to keen on positive and negative, since it's not clear (from the UI) where the origin is, and which direction is +x (it's to the right).   

Digging around in the code,  the first focal point is the one to the right of the lens, the second to the left of the lens. So I'm going to go with "left focal point" and "right focal point", since that's where they appear, relative to the lens/mirror.

**Comment by pixelzoom** [comment]
Done in the above commit - "left focal point" and "right focal point" are used throughout.

Closing.
