### ISSUE TITLE
Questions about `Guide`

### ISSUE THREAD

**Issue by zepumph** [phetsims/geometric-optics#175]
https://github.com/phetsims/geometric-optics/issues/154

1. I see that you create 4 (top/bottom per source/object). But I only ever see one pair in the sim at a time. Does there have to be 4 instances? Why don't both sets ever appear?
2. This is sorta opposite of what (1) is asking. Instead of duplicating top/bottom per source, could you suptype optic to include the guides as part of it? I feel like it makes sense from a high level to see `optic.topGuide`, and `optic.bottomGuide`. Also similar to https://github.com/phetsims/geometric-optics/issues/164

**Comment by veillette** [comment]
Here is some information for context:

There are four instantiations of GuideNodes. However, the pair (TOP/BOTTOM) of the second source position is only visible when the second source check box is on. Otherwise, the TOP/BOTTOM guides of the first source is shown. As a result, only one pair of them is shown at at time, but you can toggle between them if you check the second source box.

For reference, we used to have only two instances of guideNode, until we realized that the flash simulations toggle between the two sources (#64).

**Comment by veillette** [comment]
With regards to the second comment, we played with the idea of attaching them directly to Optic.
Two of the reasons we decided against are: Guides only exist on lenses, and not on mirrors. Optic is a relatively complex and lengthy class, and we thought it would be better to keep them seperate.

**Comment by zepumph** [comment]
>As a result, only one pair of them is shown at at time, but you can toggle between them if you check the second source box.

Since only one guide is shown at a time, it is confusing to me that there are two instances of the guide pairs. 

>Guides only exist on lenses, and not on mirrors. Optic is a relatively complex and lengthy class, and we thought it would be better to keep them seperate.

Perhaps a subtype for lens then which includes these guides?

**Comment by veillette** [comment]
Since there the visibility of the guides is swapped, one alternative approach would be to create only a top and bottom guide with a "sourcePositionProperty" that would be swappable. It seems that DynamicProperty would support this kind of interaction.

We can subtype it for lens that would include the guides.

**Comment by pixelzoom** [comment]
Most of this issue is now irrelevant, and the guides code has been reworked.

The part that is still relevant is that only 1 pair of guides is visible at a time. That seems odd/unnecessary, so we'll examine our options in https://github.com/phetsims/geometric-optics/issues/276.

Closing.
