### ISSUE TITLE
Consider alternative implementations for labeling things in the UI.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#214]
Over in https://github.com/phetsims/geometric-optics/issues/199, I discovered that adding labels is very complicated.  It's totally a view thing, has nothing to do with the model, but for some reason is specified in model coordinates.  It's also very inflexible about where the label can be placed - they must be under the thing being labeled.

A better approach would be to ditch LabelsNode, and have each Node that's labeled by responsible for it's own label.

**Comment by pixelzoom** [comment]
Another option would be to handle this in GeometricOpticsScreenView.  For each Node that need to be labeled, (1) observe its bounds, move label when bounds change, and (2) link label's visibleProperty to Node's visibleProperty.

**Comment by veillette** [comment]
@pixelzoom : For perspective, we attempted to add the labels directly to each node, but without much success. As you point out, attaching the labels to the node makes the location of them much easier, but we ran into multiple issues with this approach. 

The main issue is the constraint from the design team that the label size stays constant while zooming in and out.  When the nodes are responsible for their own labels, one would need to undo the scaling of the node when zooming by scaling the child label in the opposite direction such that it is rendered the same size while zooming.  

In the end, we decided to put the labels outside of the playArea, therefore we do not have to worry about the sizing of the label, only the positioning. As you found out the the positioning of the labels is more tricky since you need to find the position relative to a parent node that is scaled.  To get around it, we created a modelViewTransform that allows you to locate any model position in the view outside of the scaled play area.

**Comment by pixelzoom** [comment]
Thanks for the perspective @veillette, great information.  I hadn't thought about the "zoom" aspect.  I may pursue the option that I mentioned in https://github.com/phetsims/geometric-optics/issues/214#issuecomment-929529711, which woulld allow associating labels with there Nodes without the need for a modelViewTransform, keeping everything in view coordiantes.

**Comment by pixelzoom** [comment]
The implementation has been changed quite a bit --- there's now a "labels Node" for each "scene".   There are still some things that are maddeningly difficult, like putting a label _above_ an arrow instead of below it.  But I'm going to leave this where it is, and call it good.  Closing.
