### ISSUE TITLE
Problems with "Second Point" checkbox.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#218]
For #196, we changed a checkbox label from "Second Source" to "Second Point".   We did this because a 2nd point of interest on an Object is not a "second source".   

But we still have a problem here - the icon on the checkbox.  

When we've selected an Object from the combo box, the checkbox label and icon make sense:

<img width="1132" alt="screenshot_1321" src="https://user-images.githubusercontent.com/3046552/136091316-51f1260a-d6af-4a9d-8aaf-83cf86c5f003.png">

When we've selected "Light" from the combo box, the checkbox label sort of makes sense. But the icon is very incorrect, because it's showing the red circle that's used for the 2nd point of interest on an Object:

<img width="1134" alt="screenshot_1322" src="https://user-images.githubusercontent.com/3046552/136091445-7009b949-18f5-40ca-a583-a32e431d5e82.png">

@arouinfar @ariel-phet thoughts on what to do here? Should we change the label and icon on this checkbox to match Object vs Light?  If so, why should selecting a enabling the 2nd point of interested also add a 2nd light source?  I really dislike controls whose labels change, and are overloaded like this ...

Or maybe when selecting "Light", we should disable the "Second Point" checkbox, always show 2 lights, and provide a control (on the lights) for turning them on and off?

**Comment by ariel-phet** [comment]
@pixelzoom @arouinfar honestly I think it is fine as is (especially for the prototype). It is a "red thing" in both cases, I doubt there will be any confusion. My suggestion would be to punt for now. We can always see if interviews identify a problem.

As an alternative (but I do not think necessary for the prototype) we could have two check boxes up by the "object" combo box, one for "second point" and one for "second source" so that the check boxes are not overloaded, and we just disable the "second source" checkbox when objects are being used, and the "second point" checkbox when the light source is being used

**Comment by pixelzoom** [comment]
OK, then nothing to do here. Closing.
