### ISSUE TITLE
Address aliasing of lamp images

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#221]
Over in https://github.com/phetsims/geometric-optics/issues/14#issuecomment-940641334, @arouinfar noted some aliasing of the lamp images.  We decided it was good enough for the prototype, but would like to improve things for the public version.   That's going to be part of a bigger cleanup effort related to how light sources are implemented.

**Comment by pixelzoom** [comment]
The sim is approaching "feature complete", so time to address this.

**Comment by arouinfar** [comment]
@pixelzoom do you have any thoughts about how we can address the aliasing? Should I try exporting a high-dpi image at the resolution used in the sim? Let me know what size you'd like the image to be and I can send you new .png assests.

**Comment by pixelzoom** [comment]
The current size of light1.png and light2.png is 118x125, and they are scaled by 0.5 in the sim. 

They look pretty jaggy when viewed in WebStorm's viewer:  

<img width="404" alt="screenshot_1607" src="https://user-images.githubusercontent.com/3046552/157999258-6827348b-948a-475d-84d2-e81e10d23fd6.png">
<img width="282" alt="screenshot_1606" src="https://user-images.githubusercontent.com/3046552/157999259-382a71e6-ef4b-4656-afb7-a72bbb37e0b8.png">

... and macOS Preview:

<img width="404" alt="screenshot_1607" src="https://user-images.githubusercontent.com/3046552/157999271-e9c2641d-88c5-4286-a890-7638fdc428e8.png">
<img width="282" alt="screenshot_1606" src="https://user-images.githubusercontent.com/3046552/157999272-a309acaf-f0b3-48a1-ae34-8468c7589545.png">

So this might be as simple as trying to export them again at the same dimensions, with different settings in Illustrator.  Experiment, open in macOS Preview, and see if it looks any better.

**Comment by arouinfar** [comment]
Note to self: update color of red lamp to `rgb( 255, 85, 0 )`.

**Comment by arouinfar** [comment]
Things I've tried, but don't seem to make any difference in the image quality:
* Sizing the artboard the exact dimensions of the artwork to be exported
* Ensuring coordinates of artboard and artwork are integer values
* Exporting artwork at 72ppi and 150ppi (obviously resolution is different, but the quality is not)
* Comparing Type Optimized (Hinted) and Art Optimized (Supersampling) anti-aliasing

| Current Artwork | Example 1 | Example 2 | 
| --- | --- | --- |
| ![light1](https://user-images.githubusercontent.com/8419308/160479559-5836101f-0edc-40db-8ea0-b5bb25ea9777.png) |  ![150ppi_lamp-1](https://user-images.githubusercontent.com/8419308/160479587-37de093c-9602-4d1e-8815-880b8ec797a7.png) | ![realigned_lamp-1](https://user-images.githubusercontent.com/8419308/160479708-24185791-40cc-4d32-b77a-f49e7e395320.png) |

Unfortunately, I'm all out of ideas, so I suppose we'll live with the aliasing. However, light2 needs updating so its color matches the Second Point. Since there are slight changes to artboard dimensions and alignment due to the above experimentation, I'm providing new assets for both lights to keep things in sync.

Here they are: [updated-assets.zip](https://github.com/phetsims/geometric-optics/files/8384331/updated-assets.zip)

**Comment by pixelzoom** [comment]
Since we're going to need another RC (1.1.0-rc.3), I'm going to add this to that RC.

**Comment by pixelzoom** [comment]
Changes in master and 1.1.  Ready for verification in 1.1.0-rc.3.

**Comment by pixelzoom** [comment]
To verify in 1.1.0-rc.3:

1. Go to Lens screen
2. Select "Light" from combo box.
3. Check "Second Point" checkbox.
4. Verify that the color of the second light (the PNG image) is the same as the color at its associated light rays, and the icon next to the "Second Point" checkbox.

It is sufficient to verify on 1 platform.

Please close after verifying.

**Comment by KatieWoe** [comment]
Looks good in rc.3
