### ISSUE TITLE
Add a flat mirror

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/geometric-optics#227]
In playing with the sim today, I was desiring to take the mirror flat. So adding this for consideration as we think about the final improvements after the prototype. Physics is basically just a virtual image behind the mirror and equidistant and same size as the object. Suggestion would be a third scene on mirror that was flat. Note - I haven't thought thru all the issues this suggestion may bring up. Just thinking about how flat mirrors are a pretty common goal/topic and what is in everyone's everyday life all the time.

**Comment by arouinfar** [comment]
For https://github.com/phetsims/qa/issues/723

**Comment by veillette** [comment]
In the way we implement th ray tracing and the images, a flat mirror shares many similarity with a diverging mirror with an extremely long radius of curvature.  Setting the max value of the radius of curvature to 100 000 cm, we can see that the model for the image behaves well and the ray tracing works correctly.   
![image](https://user-images.githubusercontent.com/7633344/138193535-ffb0cb71-8318-4342-adb8-bfe407420d77.png)

**Comment by pixelzoom** [comment]
That's good news that the model behaves like a flat mirror when given a large radius of curvature.  

But it's one thing to poke a very large value into the code, and another thing to make it work in practice.  Among the problems we would need to address are:
* How to set radius of curvature to this very large value when that Property is constrained to a smaller range.
* How to handle a 3rd "curve type" which is neight concave or convex, and chase down all the `isConvex` and `isConcave` tests that appear in logic.
* What to do with the radius of curvature control when the user selects "flat" for the mirror. (Hide it? Disable it with a bogus value showing?...)

**Comment by pixelzoom** [comment]
For a flat mirror, change the Diameter label to "Height" in the Basics  version of the sim.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/geometric-optics/issues/255, we added an option to replace ROC+IOR controls with a Focal Length control.  I'm wondering what we should do with the Focal Length control when 'flat' mirror is selected.  Hide the control? Change it to a read-out that shows infinity? Something else?

**Comment by pixelzoom** [comment]
Discussed with @arouinfar.  When 'flat' mirror is chosen, hide ROC and Focal Length controls. There's not much value in showing the (fixed) infinity value, and it would be a significant amount of work.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/geometric-optics/issues/227#issuecomment-949048738, we had decided:
> * Hollywood this, using a large ROC for a concave (converging) mirror, as @veillette demonstrated ...

@veillette had used a large _positive_ ROC, so that's actually a _convex_ mirror.  And that seems to make the most sense, because flat and convex mirrors both produce (solely) virtual images.  Let me know if that is not correct.

If you inspect `focalLengthProperty` and `radiusOfCurvatureProperty` in Studio, you'll see that they are both "POSITIVE_INFINITY", the serialization of `Infinity`.   I'm using actual (physically-correct) values for these Properties, then mapping them internally to very large values (focal length = 100000, ROC = 2000000).  I have a slight concern about using actual (infinite) values.  PhET-iO clients will need to make sure that their programs can handle `Infinity`, which is not always straightforward (but builds character :)  

We should also revisit the initial position of the optical object in the Mirror screen. If you go to the Mirror screen and select 'flat' mirror before moving the object, the optical image is outside the visible bounds of the screen.

@arouinfar ready for review.  Let me know what you'd like to change.

**Comment by arouinfar** [comment]
The flat mirror looks great. It's a bit odd for it to be off-center, but for consistency, I know that it needs to stay in place. However, for Basics, I think we should center the flat mirror in the play area since it's the only type of mirror.

> If you inspect `focalLengthProperty` and `radiusOfCurvatureProperty` in Studio, you'll see that they are both "POSITIVE_INFINITY"

This looks good in Studio and I think it's best to use the real values in the model. Looks like `twiceFocalLengthProperty`, `right2FProperty` and `left2FProperty` are all using the very large view values, though. Not sure if this is an oversight or expected.  

> We should also revisit the initial position of the optical object in the Mirror screen. If you go to the Mirror screen and select 'flat' mirror before moving the object, the optical image is outside the visible bounds of the screen.

Agreed. The tricky part will be keeping the image position on-screen for all 3 types of mirrors. Shifting the object closer to the mirror will ensure the image of the flat mirror is starts on-screen, but will push the image of the concave mirror off-screen. An initial position of { "x": -130, "y": 72.5 } looks pretty good to me if we reduce also the initial ROC to 180 cm.

<img width="642" alt="image" src="https://user-images.githubusercontent.com/8419308/155061541-22911581-472f-44d9-8be1-55b3f22ca3ee.png">
<img width="641" alt="image" src="https://user-images.githubusercontent.com/8419308/155061560-4ad0e624-d43f-494c-a48a-5dad27e38852.png">

**Comment by pixelzoom** [comment]
> This looks good in Studio and I think it's best to use the real values in the model. Looks like twiceFocalLengthProperty, right2FProperty and left2FProperty are all using the very large view values, though. Not sure if this is an oversight or expected.

I can certainly pull that off. But I'll need to add 5 Properties.  For any Property that can have value `Infinity`, I need to add a derived (and uninstrumented) "finite" Property.  Here are the 5 Properties that can have value `Infinity`, and the 5 "finite" Properties that I'll need to add:

* `leftFocalPointProperty`, `finiteLeftFocalPointProperty`
* `rightFocalPointProperty`, `finiteRightFocalPointProperty`
* `this.twiceFocalLengthProperty`, `this.finiteTwiceFocalLengthProperty`
* `this.left2FProperty`, `this.finiteLeft2FProperty`
* `this.right2FProperty`, `this.finiteRight2FProperty`

**Comment by pixelzoom** [comment]
>  An initial position of { "x": -130, "y": 72.5 } looks pretty good to me if we reduce also the initial ROC to 180 cm.

That seems to work for the framed objects. What initial positions do you want for the 2 arrows?

**Comment by pixelzoom** [comment]
@arouinfar and I met on Zoom to adjust the initial positions of objects in the Mirror screen, as well as the initial ROC and focal length.  Those changes are in the above commit.

As for the issue of showing physically-correct values as discussed in https://github.com/phetsims/geometric-optics/issues/227#issuecomment-1047445905 ...  This is a slippery slope.   There are at least 7 such Propertes: focalLengthProperty, radiusOfCurvatureProperty, leftFocalPointProperty, rightFocalPointProperty, twiceFocalLengthProperty, left2FProperty, right2FProperty.

(1) Show physically-correct values for all Properties. This is more development work, makes the code more difficult to understand, and requires documentation warning the client that their programs need to handle `Infinity`.

(2) Show physically-correct values for focalLengthProperty and radiusOfCurvatureProperty,  finite (Hollywood) values for the others. This is less development work than (1), and is inconsistent: it still makes the code difficult to understand, and still requires documentation warning the client that their programs need to handle `Infinity`.

(3) Show finite (Hollywood) values for all Properties. This is the least amount of development work, and the code is easiest to understand. Client documentation is still needed, but telling them to interpret very-large values as "infinity".

We're currently doing (2), which I think is the least desirable option.  I'm not going to do anything further about this until @arouinfar and @kathy-phet have discussed.

**Comment by arouinfar** [comment]
@kathy-phet can you take a look at this issue when looking over Geometric Optics?

**Comment by arouinfar** [comment]
@pixelzoom I'm leaning towards option (3).  I just don't think (1) is worth the hassle and (2) is increasingly strange, especially now that we expose the `magnificationProperty` in the tree. For the flat mirror, the magnification is not exactly 1. This is not unexpected given the approach of approximating the flat mirror with a large ROC.

**Comment by pixelzoom** [comment]
Would you like me to implement (3), or are we still waiting for input from @kathy-phet?

**Comment by pixelzoom** [comment]
@arouinfar I agree.  (1) is a slippery slope.

Would you like me to implement (3), or are we still waiting for input from @kathy-phet?

**Comment by arouinfar** [comment]
Let's proceed with (3) @pixelzoom.

**Comment by pixelzoom** [comment]
Done in the above commit. @arouinfar please review in master.

**Comment by arouinfar** [comment]
Looks good in master, thanks @pixelzoom
