### ISSUE TITLE
Consider reducing opacity of virtual image (or changing opacity algorithm)

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/geometric-optics#232]
In some circumstances the opacity of the virtual image is not clearly distinct from that of the object. I am not sure how the mapping is done currently but perhaps it can be tweaked to work more clearly over a better range. For instance, in the following circumstance the image seems nearly the same opacity as the object, and might be slightly confusing without the labels.

![virtual image](https://user-images.githubusercontent.com/4051174/137381566-09c599e2-428a-4d07-97e5-64686e1e18a6.PNG)

**Comment by veillette** [comment]
Clearly the current opacity algorithm is quite arbitrary. It is an improvement on the flash simulation that merely took the size of the optic into consideration.

One constraint to consider is that the opacity needs to cover a large dynamic range of situations (change in diameter and change in scale) while having a image that is not too faint as to appear ghostly.  This partly the reason why the distance factor goes as 1/scale rather than 1/scale^2.

**Comment by pixelzoom** [comment]
FYI, the opacity algorithm is still the same as what @veillette described in https://github.com/phetsims/geometric-optics/issues/232#issuecomment-948123740.  The code looks a little different because it's now in TypeScript, and can be found in Target.ts.

**Comment by pixelzoom** [comment]
The concern that @ariel-phet raised was:
> In some circumstances the opacity of the virtual image is not clearly distinct from that of the object. 

In other words, the image is too opaque.

Can that be addressed by simply changing the range of the opacity algorithm? The range is currently [0,1], where 1 is fully opaque and 0 is fully transparent.  How about if we change that range to something like [0,0.8], so that there is always some noticeable transparency?  @ariel-phet would that address your concern? Or do you have suggestions for how to modify the algorithm that @veillette described?

**Comment by pixelzoom** [comment]
Above, I asked:
> Can that be addressed by simply changing the range of the opacity algorithm?

To help answer that question, I've added `?imageOpacityRange`.  The default is `imageOpacityRange=0,1`.  The first number is the min, the last number is the max.  The range for both values is [0,1], with 0 fully transparent, 1 fully opaque.  You may wish to also adjust `?imageMaskOpacity`, which was added for #300.

@ariel-phet would you mind test driving this? Is there a range that addresses this issue? Or do we need to make more substantial changes to the algorithm?

**Comment by pixelzoom** [comment]
Also worth noting... The title of this issue includes "... of the virtual Image ...".   But the opacity algorithm is used for _all_ Images, real and virtual.  If you want to do something for real vs virtual, that will need to be added.

**Comment by pixelzoom** [comment]
Another related question... When I add the Object arrow representation, should its Image use the same opacity algorithm as the Images associated with framed Objects?

**Comment by arouinfar** [comment]
@pixelzoom @ariel-phet the current opacity algorithm makes sense to me. It should depend on how much light hits the optic (diameter) and how large the image is (magnification). I don't see an issue with the image opacity in @ariel-phet's example in https://github.com/phetsims/geometric-optics/issues/232#issue-1026735702, because as @veillette pointed out, the diameter is likely at (or very near) its max and the image is smaller than the object. @ariel-phet if you would like to tinker with the query parameters that @pixelzoom created, please do -- I am open to suggestions.

@pixelzoom I do not think we should be treating the opacity of the images differently on the basis of real vs. virtual, framed vs. arrow.

**Comment by ariel-phet** [comment]
@pixelzoom I agree with @arouinfar that the arrow representation can follow the same opacity algorithm

Although I do not disagree with @veillette logic that the image could be quite bright, I do think from a presentation/pedagogical point of view it is nice to maintain some opacity for the image to disambiguate it from the object. 

To my eye using `?imageOpacityRange=0,0.75` works very nicely in all cases, and requires no adjustment of the default mask opacity discussed in #300 

Testing this link https://phet-dev.colorado.edu/html/geometric-optics/1.1.0-dev.20/phet/geometric-optics_en_phet.html?imageOpacityRange=0,0.75 --

1. The optic axis and rays always are visible in a nice way

2. The transparency of the image still changes in an obvious way when I change the diameter of the optic

3. I see a nice bit of transparency (though subtle) for even extreme cases, that helps for disambiguation, for instance:

Opacity allowed to go to 1
![Full opacity](https://user-images.githubusercontent.com/4051174/151054718-302656d8-8d78-47cf-882d-e84a11e0df56.PNG)

Opacity capped at 0.75
![capped opacity](https://user-images.githubusercontent.com/4051174/151054770-0fdda153-48e6-4c90-ac86-40befb147942.PNG)

So my recommended range would be 0-0.75 and leave the current default `imageMaskOpacity`

**Comment by pixelzoom** [comment]
Thanks @ariel-phet.  Change default to `?imageOpacityRange=0,0.75` in the above commit.

@arouinfar if this looks OK to you, feel free to close.

**Comment by arouinfar** [comment]
Thanks for updating @pixelzoom. Initially, 0.75 sounded a bit low to me, but it looks really good in master so I'll close.
