### ISSUE TITLE
labelBackgroundFill color should match screenBackgroundColor

### ISSUE THREAD

**Issue by arouinfar** [phetsims/geometric-optics#239]
For https://github.com/phetsims/qa/issues/723

Looks like labelBackgroundFill didn't get updated in #182 due a typo on my part and I missed it in reviewing.

@pixelzoom please make labelBackgroundFill in the default profile black. (Current alpha levels and projector mode are fine.)

**Comment by pixelzoom** [comment]
Let's do this for the prototype, adding milestone.

**Comment by pixelzoom** [comment]
@arouinfar and I discussed this on Zoom.  Since we generally want the label background to be the same as the screen background, we decided to delete `labelBackgroundFill` and use `screenBackgroundFill` for the labels, then use option `opacity: 0.5` for the labels.  This will ensure that the background color for labels and screen will remain the same forever and ever :)

@arouinfar please review in master.
