### ISSUE TITLE
Drag bounds for all objects

### ISSUE THREAD

**Issue by sarchang** [phetsims/geometric-optics#26]
- [ ] **Optic**: can only move up and down in the middle, should remain above the control panel
- [x] **Projector screen**: never moves to the left of the optic, must stay inside dev bounds (unsure if it can cover control panel)
- [ ] **Object**: never moves to the right of the optic, must stay inside dev bounds, cannot cover control panel
- [x] **Rulers**: anywhere inside dev bounds

**Comment by veillette** [comment]
The optical element is now constrained to move vertically.

**Comment by sarchang** [comment]
I was able to constrict the dragging of the rulers to within a 1x1 box but wasn't able to figure out where to access the dev bounds of the sim. 
@veillette

**Comment by veillette** [comment]
Thanks @sarchang . 
I see that the ruler is drag bounds to a 1m by 1m square. It is a good first step.

For RulerNode, you are passing an argument This.dragBoundsProperty that does not exist.

We will need to pass the layoutBounds in the constructor in order to make the bounds more practical.

Since we will take out the ruler from the PlayAreaNode, we dont need to worry about the effect of the zooming on the dragBounds.

**Comment by veillette** [comment]
In the commit https://github.com/phetsims/geometric-optics/commit/accede68b1bd1539330546825e2e568f5d0c270b, I generalized the dragBounds behavior. The rulerNode takes the layoutBounds and generate some dragBounds from it. There was some subtleties in how to handle the rotated ruler since the control point in this case is at the bottom left of the ruler.

**Comment by veillette** [comment]
Now the ruler is dragBounds to the layout Bounds. 

I think I may have missed the mark. I wondered if the rulers should be bounds to the visibleBounds rather than the layoutBounds. (devBounds) 

@arouinfar , what was the decision with regarding the dragBounds  behavior?

**Comment by sarchang** [comment]
first major tick mark of ruler should be always be inside visible bounds
full width of ruler should be inside visible bounds

**Comment by veillette** [comment]
We have set about two major tick marks to stay within the visible bounds. However we have still to attach a listener to the dragBounds to prevent losing the rulers when changing the visibleBounds.

**Comment by sarchang** [comment]
Projector screen drag bounds doesn't work with zoom

**Comment by sarchang** [comment]
- optical axis and center of optic should go from top of control panel to bottom of combo box (this means half of the optic will be underneath control panel/combo box) ----- same for all objects
- optic should also be bound by visible bounds (center gets bumped up when zooming in)

**Comment by veillette** [comment]
I have written in GeometricOpticsScreenView a new property , that determines the visibleDrag Bounds in model coordinates (which are correct even when the zoom is changed).

````
   // @protected {Property.<Bounds2>} visibleModelBoundsProperty
    this.visibleModelBoundsProperty = new DerivedProperty( [ this.visibleBoundsProperty, this.zoomModelViewTransformProperty ],
      ( visibleBounds, zoomModelViewTransform ) => {
        return zoomModelViewTransform.viewToModelBounds( visibleBounds );
      } );
````

I have applied it to ProjectorScreenNode and it works well.

**Comment by veillette** [comment]
oops, the position of the optic is hard coded. This doesnt work for the mirror

**Comment by veillette** [comment]
The "main" object is now  bound properly although there is work to be done to ensure that the movable point (with light source) is dragbounded. as well.

**Comment by veillette** [comment]
Tracking the remaining issues in #57 and #58.
