### ISSUE TITLE
User request: show position of 2f and C

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/geometric-optics#274]
> Suggestion:  When you check the “Labels” box, it would be great if you could show the position of 2f (twice the focal length) for the lens and C (center of curvature) for the mirror.  This would allow students to view trends for comparing the image when the object is at different locations.  For example, when the object is at 2f with a converging lens, the image is the same size as the object.  If the object is beyond 2f instead, the image is smaller, etc.

It sounds like 2f might already be added via https://github.com/phetsims/geometric-optics/issues/17.

**Comment by pixelzoom** [comment]
The user seems confused about f vs F. In optics`f` is the focal _distance_, `F` is the focal _point_.  We cannot "show the position of 2f" because because you cannot show the position of a distance. Do they mean show the position of `2F`, as we do for `F`?  Or do they mean show the distance `2f `as (for example) a dimensional indicator? And should we also show the distance `f`?

As a side note, a deficiency of this sim (imo) is that it does not teach the difference between `f` and `F`, and those labels are in fact never shown.

Note that there's a `show2F` query parameter that puts yellow dots at the 2F points. It's not clear what it's intended to be use for (I inherited it) and it's an internal (private) query parameter.

**Comment by pixelzoom** [comment]
Here's a screenshot with `?show2F`:

<img width="1079" alt="screenshot_1451" src="https://user-images.githubusercontent.com/3046552/144939870-071180d2-4a28-4bf9-be0f-22de8fa1a2e4.png">

**Comment by pixelzoom** [comment]
Also wondering why we'd show C (center of curvature) for the mirror, but not for the lens? 

If we're going to show C for the mirror, do we also need to show it's vertex A? A is the point on the mirror's surface where the optical axis meets the mirror.  ROC is the distance from A to C. F is the midpoint between A and C.

**Comment by ariel-phet** [comment]
@pixelzoom yes the user does mean the `2F` points. The "two f" language is used pretty colloquially in optics. If you place an object at the 2F points the image is basically a faithful reproduction of the object  for a simple lens (same size), so it might be useful to show to answer your question of what it would be used for. Basically a handy reference point for comparing magnification with a single converging lens. Outside the 2f distance the image is smaller than the object, inside that distance the image is larger than the object, so the 2F points are handy landmarks.

We would likely (as you have pointed out) need to adjust the labels. We would label the points `2F` as you suggest, that might be clear enough from context, but we might then consider changing `Focal Point` to something like `Focal Point (F)`. Probably the team needs to decide if this feature remains with a query parameter or perhaps is included by default or tied to another checkbox, ie having the 2F points appear when you click "Labels", although I think that could be a bit surprising. If we are going to include this feature by default, my personal vote would be to add another checkbox, and increase the vertical height of the bottom panel since the vertical freedom to move objects in the sim is not crucial, we can invade that space more IMO.

I don't think disambiguating `F` vs `f` is a major learning goal for us, but agreed that we should use the standard notation where appropriate.

A for the mirror and showing its center, I will need to think on that a bit more, but no need to show the center for the lens.

**Comment by pixelzoom** [comment]
At 12/16/21 check-in, @ariel-phet said that he can imagine something related to this being included in the Basics version, but perhaps not in the full version.

**Comment by pixelzoom** [comment]
12/20/2021 design meeting, notes from the [design doc](https://docs.google.com/document/d/1hVxM-ax2UyxctbclAhutrRad5A0eeLWKFQNB4U7ls4o/edit#heading=h.239xgh85ukkm).

> 2F
> - Are they labelled?
>   - Yes, “2F”. Change focal point to “Focal Point (F)”.
> - Do they have a separate control?
>   - Checkbox “2F Points” just under “Focal Points (F)”
>   - Rename “Focal Points (F)”
> - What do they look like?
>   - Same color as F, but small solid circle with black stroke. Same size as Second Point.
> 
> Which sims?
> - Learning goal to discover the point where object and image are the same size (2F). Adding a checkbox to the full version impacts this learning goal.
> - Would we call it C or 2F for the mirror? Curvature is likely Hollywooded, so might not want to call it C if it’s not C. Better to have a consistent language across screens. Teacher can handle the C vs. 2F discussion.
> - Query parameter boolean show2F. Default true on Basics, default false on full version.

**Comment by pixelzoom** [comment]
@arouinfar ready for review.

Notes:

* The query parameter is `enable2F` (not `show2F`), because it enables the 2F feature, it does not necessarily make the 2F points initially visible.  It defaults to `false` in the full version, and will eventually default to `true` in the Basics version.  To test, you'll need to run with `enable2F=true`.

* By default, the "2F Points" checkbox is unchecked.  Let me know if you'd prefer otherwise.

* The names of JavaScript identifiers cannot start with numbers. So names like `2FProperty` and `2FPointsCheckbox` are not possible, and it may consequently be a little more difficult to find things in Studio.
 
* There are a number of new PhET-iO elements for review:

```
// Lens screen
geometricOptics.lensScreen.model.lens.twiceFocalLengthProperty
geometricOptics.lensScreen.model.lens.left2FProperty
geometricOptics.lensScreen.model.lens.right2FProperty
geometricOptics.lensScreen.view.controlPanel.checkboxGroup.twoFPointsCheckbox.*
geometricOptics.lensScreen.view.visibleProperties.twoFPointsVisibleProperty

// Mirror screen
geometricOptics.mirrorScreen.model.mirror.twiceFocalLengthProperty
geometricOptics.mirrorScreen.model.mirror.left2FProperty
geometricOptics.mirrorScreen.model.mirror.right2FProperty
geometricOptics.mirrorScreen.view.controlPanel.checkboxGroup.twoFPointsCheckbox.*
geometricOptics.mirrorScreen.view.visibleProperties.twoFPointsVisibleProperty
```

**Comment by arouinfar** [comment]
> The query parameter is enable2F (not show2F), because it enables the 2F feature, it does not necessarily make the 2F points initially visible. It defaults to false in the full version, and will eventually default to true in the Basics version. To test, you'll need to run with enable2F=true.
 
Sounds good to me. I took `enable2F=true` for a test drive in master and it looks good and behaves as expected.

> By default, the "2F Points" checkbox is unchecked. Let me know if you'd prefer otherwise.

I would default to unchecked in all flavors.

> The names of JavaScript identifiers cannot start with numbers. So names like 2FProperty and 2FPointsCheckbox are not possible, and it may consequently be a little more difficult to find things in Studio.

I like the choices you made for phetioIDs. Luckily, the autoselect feature in Studio will make it easy to find the elements in the tree by hovering over them in the sim.

> I added "2F" for the label that's shown when "Labels" checkbox is checked.

Perfect, looks good.

> There are a number of new PhET-iO elements for review:

The phetioIDs look good and things behave as expected. The only thing that looks extraneous is `geometricOptics.*Screen.view.twoFPointsNode`. It's a container for a single linked property -- `geometricOptics.*Screen.view.visibleProperties.twoFPointsVisibleProperty` which is the property that drives the 2F checkbox. I don't think `twoFPointsNode` really adds any benefit to the tree, so I think we could delete it if @pixelzoom doesn't have any objections.

**Comment by pixelzoom** [comment]
Since visibleProperty was added to Node options, the recommended pattern is to link the Node's visibleProperty to the Property that's controlled by (for example) CheckBox.  And we include the Node in the Studio treee because the instructional designer is more likely (for example) to look for `twoFPointsNode` than  `view.visibleProperties.twoFPointsVisibleProperty`.   So I think we should keep `twoFPointsNode` in the tree.  If I remove it, I think I'm highly likely to be asked to add it later.  We can revisit later if you'd like, when we're polishing the Studio tree.

Since that was the only outstanding ask, I'm going to close this issue.

**Comment by oliver-phet** [comment]
Can we keep this issue open until the version that supports `enable2F=true` is published (so that I can notify the user that sent in the original request)?

**Comment by pixelzoom** [comment]
Certainly.  That's likely to be sometime in May 2022.   So I'm unassigning and labeling as "on-hold".

**Comment by pixelzoom** [comment]
This feature is now live in Geometric Optics 1.1, which was published today (4/6/2022) at
https://phet.colorado.edu/sims/html/geometric-optics/latest/geometric-optics_en.html

By default, this feature is off (hidden).  Turning it on adds a "2F Points" checkbox to the control panel.  There are 2 ways to turn it on:

(1) Go to the PhET menu (lower right), and choose the "Options" menu item to open the Options dialog. In the Options dialog, check the checkbox that is labeled "Add 2F Points checkbox to control panel".

(2) Run the sims with `?add2FPointsCheckbox=true` appended to the URL, like this:
https://phet.colorado.edu/sims/html/geometric-optics/latest/geometric-optics_en.html?add2FPointsCheckbox=true

@oliver-phet please commmunicate with the user who suggested this feature, then please close this issue.

**Comment by oliver-phet** [comment]
User emailed!
