### ISSUE TITLE
FocalPointNode should extend PlusNode

### ISSUE THREAD

**Issue by veillette** [phetsims/geometric-optics#29]
The PlusNode is attached as a child whereas it could be better if FocalPointNode was extending PlusNode

**Comment by veillette** [comment]
The constructor should also take an option argument that can be then passed to the super class.

**Comment by sarchang** [comment]
FocalPointNode now extends PlusNode instead of Node.  I added the options argument in the constructor, passed it into super, and replaced FocalCrossNode with super.  There are two commits because I forgot to delete a line I had commented out temporarily and then there was a merge conflict, so hopefully this works okay now.

**Comment by veillette** [comment]
Well done @sarchang . I added a bit of documentation to the listeners and rewrote the description of the scenery node. 

The second commit was about the use of this.center over super.center .  Both work but it is more traditionally to center the node directly than through the parent class.

Very clean commits, and github hygiene.

**Comment by veillette** [comment]
We are done here. Closing
