### ISSUE TITLE
Instrument all labels for checkboxes and radio buttons.

### ISSUE THREAD

**Issue by arouinfar** [phetsims/geometric-optics#338]
For #237 

The NumberControl and Rays subpanel titles are instrumented, but the title text for aqua radio buttons and checkboxes is not. @pixelzoom please instrument these titles. I'm pretty sure a `visibleProperty` will come along for the ride, but those should be `phetioReadOnly: true` otherwise the UI will look really odd (e.g. functional checkbox with hidden title string).

While you're in there, I'm wondering if `view.controls.controlPanel.raysSubpanel.raysText` would be better called `raysSubpanel.titleText` since "Rays" is subject to change. I'll defer to your judgment on this one.

**Comment by pixelzoom** [comment]
@arouinfar said:
> but the title text for aqua radio buttons and checkboxes is not. @pixelzoom please instrument these titles. 

I'm pretty sure that use mean "labels" here, not "titles".

**Comment by arouinfar** [comment]
As an aside, I am always asking devs to instrument this sort of label text (for example, https://github.com/phetsims/circuit-construction-kit-common/issues/870). If it's possible to do this in sun instead of in a sim-specific way, let's elevate to a common code issue and tag for phet-io meeting.

**Comment by pixelzoom** [comment]
> . If it's possible to do this in sun instead of in a sim-specific way, let's elevate to a common code issue and tag for phet-io meeting.

Most UI components (checkbox, radio button, combo box,...) take a Node as their label, so the label is not always text, may be text + icon, etc.   So it's not a simple thing to address in common code.

**Comment by pixelzoom** [comment]
@arouinfar ready for review.  

Notes:
* I instrumented the Text node for all checkbox and radio-button labels. The tandem name is `labelText`.  Each of these Nodes has a `textProperty` that is editable
* Instead of `phetioReadOnly: true` for the labels, I used `phetioVisiblePropertyInstrumented: false` to uninstrument visibleProperty entirely.  I don't see any reason for the client to be hiding checkbox labels.
* I added `phetioVisiblePropertyInstrumented: false`  to the "Rays" title, `geometricOptics.lensScreen.view.controls.controlPanel.raysSubpanel.titleText`.  You can change it's `textProperty`, but its visiblePropery is not instrumented.  Again, I don't see any reason for the client to hide this.

**Comment by arouinfar** [comment]
Thanks @pixelzoom this all looks good in master.
