### ISSUE TITLE
Show (+) label on Focal Length and ROC controls only when it's needed.

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/geometric-optics#345]
@pixelzoom @arouinfar as part of phetsims/geometric-optics-basics#7 

I am not sure if for basics we need the (+) label on the focal length. Since we only have a converging lens there is nothing to contrast this value with (in terms of being negative), so maybe this label is unnecessary here.

My instinct is we should remove it for basics, but not a strong opinion.

**Comment by pixelzoom** [comment]
Trying to determine when it's relevant to show (+) turned into a horrible mess. There are so many ways that a divering optic can be added via iO. So there's no reliable way of knowing.

The compromise is to remove the (+) altogether, in all cases.  And only show (-) when the actual focal length (or ROC) has a negative sign.  That's what I've done in the above commit. 

So in GO and GO:Basics, positive focal length (and ROC) will look like this:

<img width="209" alt="screenshot_1597" src="https://user-images.githubusercontent.com/3046552/157297354-5b1d7aca-623e-468a-aae7-21f265e6543a.png">

... and negative will look like this:

<img width="205" alt="screenshot_1598" src="https://user-images.githubusercontent.com/3046552/157297391-0c41105d-ce8a-4931-a14f-8977f1b7071a.png">

This seems like a reasonable compromise to me.  But if you don't like it, then the alternative is what we had before -- to show (+) for positive values regardless of whether negative values are possible.  Doing what we set out to do in this issue is simply not practical (or reliable, due to iO). 

@arouinfar please review, let me know you'd like to proceed.

**Comment by arouinfar** [comment]
> The compromise is to remove the (+) totally (in all cases), and only show (-) when the actual focal length (or ROC) has a negative sign. That's what I've done in the above commit.

That seems totally reasonable to me and the behavior looks good in master. 

While the `(+)` adds consistency in the labeling, I don't think it's necessary. Without it, the `(-)` may actually become more noticeable because the string change between concave and convex optics will be more signficant.
