### ISSUE TITLE
Revisit design for Guides feature.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/geometric-optics#358]
A question about the Guides feature...

I guess I can understand how they may be useful to check alignment with "Marginal" rays:

![screenshot_338](https://user-images.githubusercontent.com/3046552/156674459-b8ce0de3-18c6-408e-b89b-7712f0a28bfa.png)

But I don't understand how they are anything but confusing for the other "Rays" choices. See screenshots below.   Should we consider hiding the guides and disabling the "Guides" checkbox when Rays is anything other than "Marginal"?

![screenshot_339](https://user-images.githubusercontent.com/3046552/156674645-67ab57b2-8ddf-4707-b875-40181cc6cfd8.png)
![screenshot_340](https://user-images.githubusercontent.com/3046552/156674651-35ca47e3-f27d-41a6-b8d1-23fea6767f34.png)
![screenshot_341](https://user-images.githubusercontent.com/3046552/156674653-61e362b2-10ad-4b5c-93d8-89c85a2eb088.png)

**Comment by pixelzoom** [comment]
I'm also wondering about the Guides when "light propagation" toggle button is off.  See screenshot below.  Should guides be shown when light rays are not propagating?

I realize that the not everyone on the sim team likes the Guides feature.  But I recommend we revisit its design, even if it's going to be hidden behind a query parameter. 
 
<img width="997" alt="screenshot_1591" src="https://user-images.githubusercontent.com/3046552/157111901-d7bf196b-3cd8-46e3-b37e-48294fdbd2d1.png">

**Comment by arouinfar** [comment]
@pixelzoom @kathy-phet my understanding of the Guides is that they are intended to provide information about the extent to which light bends when traveling through a lens. The angle between the guide arms is smaller when the lens has a shorter focal length, etc.

> I guess I can understand how they may be useful to check alignment with "Marginal" rays:

If Do ~ 2f the guide arms will be well-aligned with the marginal rays. However, that's not always the case:
![image](https://user-images.githubusercontent.com/8419308/157347343-f4ea9d03-41a8-41ca-a1c5-3b3696db1364.png)

> But I don't understand how they are anything but confusing for the other "Rays" choices.

I agree that Principal Rays definitely look strange with the Guides, but I'm neutral towards Many Rays.

With "None" there can be conversations about why the image is closer/further from the lens, using the Guide for support without the need to introduce the ray representations. A natural next step would be to introduce Marginal Rays because that's what the Guides are mimicking. It's not always perfect alignment as I pointed out above, but it's generally reasonable. 

> Should we consider hiding the guides and disabling the "Guides" checkbox when Rays is anything other than "Marginal"?

I see strong reasons for using the Guides with None or Marginal. The Guides aren't fundamentally incompatible with the other ray types, so I wouldn't disable the checkbox based on the Ray selection. I don't think it would necessarily be obvious why the checkbox is sometimes disabled and could lead to UX issues.

> I'm also wondering about the Guides when "light propagation" toggle button is off. See screenshot below. Should guides be shown when light rays are not propagating?

Yes, I think it's fine to show the guides when the light isn't propagating. The angle of the guides can be useful in predicting the image location.

**Comment by pixelzoom** [comment]
Thanks @arouinfar.  So it sounds like there's nothing to do here, and the Guide will continue to be shown whenever the "Guides" checkbox is checked.  Closing.
