### ISSUE TITLE
Amount of 'Many Rays' changes

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/geometric-optics#405]
**Test device**
MacBook Air (m1 chip)

**Operating System**
12.3

**Browser**
Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/787
The amount of many rays coming from the object doubles as the object is moved away from the optic. This happens on both screens, in all scenes, and with all objects. This also happens with the second point.

Also seen in master. 

**Steps to reproduce**
1. Go to any screen and select "Many Rays"
2. Move the Object away from the Optic

**Visuals**

https://user-images.githubusercontent.com/87318828/159923800-8f250122-63d0-4d76-8b62-b37d058347e8.mp4

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Geometric Optics‬
URL: https://phet-dev.colorado.edu/html/geometric-optics/1.1.0-rc.1/phet/geometric-optics_all_phet.html
Version: 1.1.0-rc.1 2022-03-18 20:41:59 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.83 Safari/537.36
Language: en-US
Window: 1431x633
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by pixelzoom** [comment]
Thanks for reporting @Nancy-Salpepi, very observant of you!  But this behavior is both intentional and necessary.  If we don't increase the number of rays as the distance from the optic increases, then we can get many incorrect/confusing cases (like the screenshot shown below), where no rays intersect the optic, and no image is formed.  To form an optical image, the ray tracer needs at least 1 ray (preferrably 2) to intersect the optic at all times, at its minimum diameter.  More details in https://github.com/phetsims/geometric-optics/issues/289 where we noticed this problem, and decided on this solution. 

This is also mentioned in the [Ray Tracing section of model.md](https://github.com/phetsims/geometric-optics/blob/master/doc/model.md#ray-tracing):
> _Many_ rays consists of a 120-degree fan of rays. The number of rays varies with the distance of the object from the optic, such that at least 2 rays will pass through the optic.

If this makes sense to you, please close.

<img width="1040" alt="screenshot_1512" src="https://user-images.githubusercontent.com/3046552/149027355-4446882b-3ea7-4b22-9353-270df26442f9.png">

**Comment by pixelzoom** [comment]
I expanded the description in model.md a bit:

> _Many_ rays consists of a 120-degree fan of rays. The number of rays increases with the distance of the object from the optic, so that at least 2 rays will pass through the optic. At least one ray (preferrably two) must intersect the optic in order to form an image.

**Comment by Nancy-Salpepi** [comment]
Thanks @pixelzoom. The expanded description makes it super clear :)
