### ISSUE TITLE
Light spot intensity inconsistent when switching between ray types

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/geometric-optics#417]
**Test device**
MacBook Air (m1 chip)

**Operating System**
12.3

**Browser**
Safari

**Problem description**
For https://github.com/phetsims/qa/issues/793 in the lens screen, concave lens scene:
When the lamp is positioned so that only 1 marginal ray hits the screen--the screen is light yellow in color. It is that same color no matter which ray type is selected. Moving the screen so that no marginal rays hit (but other rays still do)--keeps the screen a slight yellow color.  However, if I then switch between principal and back to marginal rays, the screen is white. 

**Steps to reproduce**
1. Go to the concave scene in the lens screen
2. Select the light
3. Position the light so that its base is just above the optic axis (screen is slightly yellow)
4. Move the screen up so that no marginal rays are hitting it (screen still slightly yellow)
5. Switch to principal rays and then back to marginal rays (screen is white)
 
**Visuals**

https://user-images.githubusercontent.com/87318828/161323816-ee8937e6-5dd5-43ba-ac2e-e74acc080962.mp4

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Geometric Optics‬
URL: https://phet-dev.colorado.edu/html/geometric-optics/1.1.0-rc.2/phet/geometric-optics_all_phet.html
Version: 1.1.0-rc.2 2022-03-31 19:18:11 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15
Language: en-US
Window: 1430x710
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 256
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by pixelzoom** [comment]
Reproduced in master.

The fact that's it's not behaving consistently is a problem.  But a bigger problem is that its possible for the rays to miss the screen entirely, as in @Nancy-Salpepi's example.

@arouinfar @ariel-phet how should this behave?

**Comment by ariel-phet** [comment]
@pixelzoom I don't think it is a problem that the rays are missing the screen. Yes the "marginal rays" might be, but if you turn to "many rays" you still see rays hitting the screen. The correct behavior is that the screen should have some illumination (the slight yellow). Happy to discuss.

**Comment by pixelzoom** [comment]
Yes, let's discuss.  Scenarios like the one shown below seem problematic to me.   There is no light spot because the rays that interact with the optic do not intersect the screen.  But other rays do intersect the screen.

<img width="1104" alt="screenshot_1640" src="https://user-images.githubusercontent.com/3046552/161578108-519fc6df-a013-4c7e-a0a0-d58be53c6bc7.png">

**Comment by pixelzoom** [comment]
I discovered several other problems 

These are general problems:

* LightSpot `shapeProperty` should be in the view, and should be derived from `positionProperty` and `diameter` Property. It's currently in the model, and it's resulting in duplicated calls to `getPositionAndDiameter`.

* Clipping the light spots to the projection screen should be handled by the model, not the view. And handling it in the model is resulting in undesirable dashed stroke along the edges of the projection screen, e.g.:

![screenshot_1641](https://user-images.githubusercontent.com/3046552/161594117-163f3bff-2f48-4912-80ce-f764143a0238.jpg)




These problems affect PhET-iO:

* `lightSpot.positionProperty.x` should always be the same as `projectionScreen.positionProperty.x`, but it's sometimes slightly off, because of the use of `Vector2.blend` in LightSpot.ts `getPositionAndDiameter`.

* `lightSpot.positionProperty` is defined and documented as `Vector2 | null`, but it's never `null`.

* `lightSpot.diameterProperty` is defined and documented as `number | null`, but it's never `null`.

So... This is an aspect of the sim that I hadn't previously modifed much. But I guess it's time for some significant changes here.  Unfortunate during RC, but better not to put this off.

**Comment by ariel-phet** [comment]
@pixelzoom @arouinfar I do agree that publishing the sim as is with a known issue like this is the better choice, I think as @arouinfar says it is definitely an edge case and won't be discovered/noticed by the majority of users, and also agreed not central to the learning goals.

**Comment by pixelzoom** [comment]
I started by fixing the problems I noted in https://github.com/phetsims/geometric-optics/issues/417#issuecomment-1087794055, see the above commit to master and 1.1.   These changes were needed regardless.

> Having a slight background glow in the Many rays case isn't central to the learning goals, and I would rather not complicate things.

It seems like the consesus is not to do this. And I think that's a good consensus, because there's currently no way to do this - the screen cannot be given a glow, we'd have to decide on the glow intenstity, etc.

> ...  I do agree that publishing the sim as is with a known issue like this is the better choice ...

To clarify... This "known issue" is referring to the "Many" rays case that I raised in https://github.com/phetsims/geometric-optics/issues/417#issuecomment-1087701829. Correct?

And I'm assuming that we want to fix the problem originally reported by @Nancy-Salpepi. Correct?  I'm still not sure how to fix that case, and we'll need to discuss.

**Comment by pixelzoom** [comment]
Here's what's going on in the ray tracer.  When rays are animated, the ray tracer starts by making the optical image (or light spot) invisible.   It remains invisible until the ray reaches the location of the image/spot.  In the case of the light spots, the ray tracer is testing for intersection with the screen. What is should probably be doing is testing for intersection with the _vertical plane of the screen_ -- i.e., has a ray reached the x coordinate of the projector screen?  If so, make the light spots visible.

**Comment by pixelzoom** [comment]
In the above commits, I did some cleanup in LightRay.ts.  Then I changed `hasReachedTarget` to return `true` when a ray has reached the x position of the projections screen, not when it has intersected the screen.  

@Nancy-Salpepi please review in master. In addition to verifying the case that you reported in https://github.com/phetsims/geometric-optics/issues/417#issue-1190157026, please take the entire "Light" scene for a quick test drive.

Note also that we decided NOT to address the case that I asked about in https://github.com/phetsims/geometric-optics/issues/417#issuecomment-1087701829.  Only rays that interact with the lens will cast light on the projection screen. Other rays (which are essentially ambient light) are not modeled, and this will be noted in teacher tips.

**Comment by Nancy-Salpepi** [comment]
Looks fixed in master and I didn't see any other issues with the "light" scene.

**Comment by pixelzoom** [comment]
To verify in 1.1.0-rc.3, follow the steps to reproduce in https://github.com/phetsims/geometric-optics/issues/417#issue-1190157026.  Also give the "Light" scene a quick test drive.  It is sufficient to verify on 1 platform.

Please close after verifying.

**Comment by Nancy-Salpepi** [comment]
looks good in rc.3
