### ISSUE TITLE
Consider changing the Return to Toolbox keyboard shortcut

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/geometric-optics#420]
**Test device**
MacBook Air (m1 chip)

**Operating System**
12.3

**Browser**
Safari/Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/793

With full screen selected, pressing `esc` exits out of full screen instead of returning a tool to the toolbox. 

**Steps to reproduce**
1. Select Full Screen in the PhET Menu
2. Remove a ruler from the toolbox using keyboard nav
3. press `esc` to return ruler

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Geometric Optics‬
URL: https://phet-dev.colorado.edu/html/geometric-optics/1.1.0-rc.2/phet/geometric-optics_all_phet.html
Version: 1.1.0-rc.2 2022-03-31 19:18:11 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Safari/537.36
Language: en-US
Window: 1431x690
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by Nancy-Salpepi** [comment]
The same thing happens when pressing `esc` to exit a combobox or dialog (I usually tab back to the close button and press enter).

**Comment by jessegreenberg** [comment]
"Escape" is a common/intuitive close and return key but it does collide with the "exit full screen" key of the browser. There is no way to prevent the browser from exiting full screen in these cases.

I think this collision is relatively common for the web apps when using full screen. There are menus on youtube that I can close with the escape key. But if I play a video in full screen, escape exists full screen instead of closing the menu.

Thanks for pointing out @Nancy-Salpepi but I don't think anything needs to change for this. I added a note about this in qa-book.md, to be removed if @arouinfar or others disagree with this.

**Comment by arouinfar** [comment]
Thanks @jessegreenberg! Given your explanation, I am comfortable with closing this issue. Thanks for updating the QA book, as this will likely come up again.
