### ISSUE TITLE
Tools in the toolbox have Move Up/Down buttons that do nothing.

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/geometric-optics#472]
**Test device**
MacBook Air M1 chip

**Operating System**
13.3.1

**Browser**
Safari 16.4

**Problem description**
For https://github.com/phetsims/qa/issues/947, for the tool nodes, (ex. geometricOptics.lensScreen.view.tools.horizontalRulerNode) the move up/down buttons don't actually change the ordering of the tools in the toolbox. Perhaps they should be made read-only in this case?

**From Slack:**
Nancy Salpepi
  [12:38 PM](https://phetsims.slack.com/archives/D02811S7KRU/p1685032694186579)
Hello Amy!!!!!
I hope all is OK on your end!
Looking at GO, for any of the tool nodes, ex. geometricOptics.lensScreen.view.tools.horizontalRulerNode, I don’t understand what the move up/move down buttons are supposed to be doing. They aren’t changing the order in the toolbox…so I’m confused.

Amy Rouinfar
  [12:41 PM](https://phetsims.slack.com/archives/D02811S7KRU/p1685032910430789)
Weird, seems like an unintended consequence of some changes we made to the IndexedNodeIO type during development of CCK. This is what allows users to reorder things in the carousel. (edited) 
[12:42](https://phetsims.slack.com/archives/D02811S7KRU/p1685032932999189)
There’s almost certainly a paper trail on this, I’ll see if I can find it.

Nancy Salpepi
  [12:44 PM](https://phetsims.slack.com/archives/D02811S7KRU/p1685033080924059)
OK. It just seemed really odd. If you take one of the tools out, the index number changes. Tools can have the same number.

Amy Rouinfar
  [12:44 PM](https://phetsims.slack.com/archives/D02811S7KRU/p1685033097467409)
Maybe it should be read-only?
[12:45](https://phetsims.slack.com/archives/D02811S7KRU/p1685033115231479)
I think it’s related to the z-ordering of the tools in the play area, but the buttons don’t actually change anything

**Visuals**

https://github.com/phetsims/geometric-optics/assets/87318828/acfaf94a-c5f9-4f02-aa06-2e9ad1840529

**Comment by pixelzoom** [comment]
I'm super confused. Why are the **Move Up** and **Move Down** buttons even appearing in Studio?  The toolbox is just a Panel whose contents is an HBox, and each tool is a child of the HBox.  See GOToolboxNode.ts. 

@zepumph @samreid does Studio add these button for every child of an HBox/VBox? Is there a way to request _not_ to add them?

**Comment by pixelzoom** [comment]
GOToolNode (the base class for all tools) has `phetioType: IndexedNodeIO`, so that the rendering order of tools (how they overlap) is preserved in state.  Anything PhET-iO element of type e `IndexedNodeIO` gets _Move Up_ and _Move Down_ buttons in Studio.   The semantics of "up" and "down" depend on the PhET-iO element.  In the case of ComboBox and Carousel (both of which display "lists" of items), "up" and "down" control the order of items in the list.   In the case of the GO tools, the semantics of "up" and "down" is not the order of tools in the toolbox (which is not a desirable feature), it's the rendering order of tools.   And that difference is where the confusion lies. 

So... Pressing "Move Up" and "Move Down" when the tools are in the toolbox is indeed moving them up/down -- in the rendering order. But the tools do not overlap in the toolbox, so you see no visual change.  When tools are outside of the toolbox and they overlap, you will see a visual change.

I'll assign this to @arouinfar to decide if this is something that should be clarified in examples.md.  I'm OK if it's not.

**Comment by Nancy-Salpepi** [comment]
Thank you for explaining this @pixelzoom!

**Comment by arouinfar** [comment]
Thanks @Nancy-Salpepi @pixelzoom. I don't think this needs to be covered in examples.md, so I'll close.
