### ISSUE TITLE
Speed of ray animation

### ISSUE THREAD

**Issue by sarchang** [phetsims/geometric-optics#71]
How fast should the rays be drawn?

**Comment by veillette** [comment]
@arouinfar will play with the simulation.
The constant that control the speed of the rays is in GeometricOpticsConstants
```
  HORIZONTAL_SPEED: 5, // (speed in meter per second for light)
```

**Comment by pixelzoom** [comment]
`GeometricOpticsConstants .HORIZONTAL_SPEED` no longer exists.  It appears to have been replaced by `GeometricOpticsConstants.ANIMATION_TIME`.

**Comment by pixelzoom** [comment]
I've renamed the constant and documented it better.  It's now `GeometricOpticsConstants.RAYS_ANIMATION_TIME`.

**Comment by pixelzoom** [comment]
There's something very wrong with how `RAYS_ANIMATION_TIME` is being used.  If I change it to something like 0.1, then instead of the animation going faster, the animation stops before the rays have been fully rendered, for example:

<img width="998" alt="screenshot_1243" src="https://user-images.githubusercontent.com/3046552/133513252-abac9fd5-39fc-409d-9f79-3e0406ab48f3.png">

**Comment by veillette** [comment]
@pixelzoom:  There are two constants that govern the animation of the rays.

One is the speed of the rays and the other it the animation time.  The product of them gives the distance travelled.

```
  LIGHT_SPEED: 500, // speed in centimeter per second for light for the purpose of the animation
  ANIMATION_TIME: 5, // maximum animation time
```
The distance travelled should be at least larger than the width of the screen. 

The two constants, as defined, are probably not as orthogonal as they should be since  changing the animation time to a small value, one is forced to increase the speed value in order to have the rays span the screen.

**Comment by veillette** [comment]
It should be possible to have a less heuristic approach. 
The stopping of the ray animation could be determined by a leftward horizontal position, which when reached stopped the animation. 

I'll also mention that one could not set any maximum animation time and let the animation go on forever. It didn't seem to have any performance effects on our laptops but I suspect this is not the case on all devices.

**Comment by pixelzoom** [comment]
@veillette thank you for the explanation, that all makes sense.

In the above commit, I increased RAY_ANIMATION_TIME to 10 seconds, and I replaced LIGHT_SPEED with this `lightSpeed` query parameter, so that designers can experiment:

```js
  // speed of light in centimeters per second, for the purpose of the light rays animation
  lightSpeed: {
    type: 'number',
    defaultValue: 500,
    isValidValue: value => ( value >= 100 )
  }
```

@arouinfar please review, let me know if you'd like to change the default (500) to something else. Note the constraint that `lightSpeed` must be >= 100.  That seems plenty slow.  Any slower and you risk running into the problem that I described in https://github.com/phetsims/geometric-optics/issues/71#issuecomment-920401462.

**Comment by arouinfar** [comment]
The behavior in master feels pretty good to me and is sufficient for the prototype.

@ariel-phet can you test out `lightSpeed` to see if there would be a better value?

**Comment by ariel-phet** [comment]
@arouinfar @pixelzoom I have a slight preference for `lightSpeed` to be equal to 400, 500 feels a shade too fast if the goal is to kind of comfortably have one's eye trace the path of the light rays. But my preference is minor.

**Comment by pixelzoom** [comment]
I like @ariel-phet's suggestion here. Slightly slower (400) feels good to me too.    I have made it so in the above commit.  Closing.
